# Project Description

This project is a very basic neural network. The project trains a neural network to predict an output vector of dimension equal to the number of rows in the input matrix. It does this by creating random training layers and then through a series of running the input vector through those layers and changing the weights in the layers based on how wrong the ouput was it trains the model to be able to predict the output given the input.

In order to use it you can create any mxn matrix to put as the first input and any mx1 vector that consists of values 0-1 to have as the second input. The output vector that the neural network creates is traditionally also a set of weights from 0-1 that will indicate a final result so if you put values outside of the range 0-1 for the second input the algorithm will attempt to get as close as it can, that being 1, but it will be unable to accurately predict it given the fact that it is outside of the range of values the function can output.

A sample set of a matrix and a vector is provided below but feel free to play around with the values or create new matrices and vectors to test out the function just make sure it follows the format as stated above (namely make sure that the number of rows in your training matrix and output matrix are the same). Also when doing this keep in mind that the model does not reset itself as it is intended to be continually trained so if you run the same neural network over different kinds of matrices it will likely do poorly, I would recommend either restarting the kernel or creating a new class if you want to try a new dataset.

There is some explanation of the math behind this in the code but as I am not an expert if you actually wish to learn about the mechanics behind this a college student's intro to python course final project is probably not the place to do so.


Below is just a description of my neural network in comparison to what a traditional machine learning algorithm is used for.

Traditionally, neural networks would use thousands or millions of inputs with their own respective outputs. Before processing them through the neural network they would first be converted into these matrices. An example is an image could be converted to a matrix where the values represent how dark a pixel corresponding to a particular spot on the image would be. Additionally, that output vector would normally be converted to something afterwards, for instance based on the values in the output vector the neural network would say that it is a picture of a cat.

In my project I have only done the process to train the model to calculate the output vector from a given input. Currently it is sized to dimension 4 as that felt large enough to show the use of it while not making the print statements painful to read. If someone wanted to change these values they are the two instances of 4 in the __init__ function used to define the weights. Additionally, normally after training the neural network it would then be tested on a new set of data to see if it could actually predict things or if it was just tuned to the one specific set of inputs it was provided. I have not created the means to do that as all I made was the process to train it.

## Project Code

If it makes sense for your project, you can have code and outputs here in the notebook as well.

In [1]:
import numpy as np
import random
from my_module.main import simple_neural_network, sigmoid, sigmoid_derivative

In [2]:
!pytest my_module/test_functions.py

============================= test session starts ==============================
platform linux -- Python 3.9.5, pytest-6.2.5, py-1.10.0, pluggy-1.0.0
rootdir: /home/izane/FinalProject_COGS18_WI22
plugins: anyio-3.2.1
collected 3 items                                                              

my_module/test_functions.py ...                                          [100%]

============================== 3 passed in 0.84s ===============================


In [3]:
X=np.array(([0,0,20,3],[0,17,1,2],[6,0,1,5],[1,3,1,1],[1,0,0,1],[3,7,1,0]), dtype=float)
y=np.array(([0],[0.2],[0],[0.4],[1],[0.6]), dtype=float)

In [4]:
NNexample = simple_neural_network(X,y)

In [5]:
NNexample.training(2000)

Epoch: 
0
Output: 
[[0.96409183]
 [0.96081094]
 [0.96065351]
 [0.9512348 ]
 [0.89604455]
 [0.95754497]]
Error: 
[[-0.96409183]
 [-0.76081094]
 [-0.96065351]
 [-0.5512348 ]
 [ 0.10395545]
 [-0.35754497]]
Mean Squared Loss: 
0.47894440771822056


Epoch: 
200
Output: 
[[0.07265981]
 [0.22757439]
 [0.11956285]
 [0.28008082]
 [0.68974203]
 [0.39994819]]
Error: 
[[-0.07265981]
 [-0.02757439]
 [-0.11956285]
 [ 0.11991918]
 [ 0.31025797]
 [ 0.20005181]]
Mean Squared Loss: 
0.028499402251796268


Epoch: 
400
Output: 
[[0.03821444]
 [0.20148065]
 [0.0869915 ]
 [0.33934482]
 [0.85289375]
 [0.51695434]]
Error: 
[[-0.03821444]
 [-0.00148065]
 [-0.0869915 ]
 [ 0.06065518]
 [ 0.14710625]
 [ 0.08304566]]
Mean Squared Loss: 
0.006874322664221108


Epoch: 
600
Output: 
[[0.02726613]
 [0.20478689]
 [0.07005434]
 [0.35554331]
 [0.89878923]
 [0.54373659]]
Error: 
[[-0.02726613]
 [-0.00478689]
 [-0.07005434]
 [ 0.04445669]
 [ 0.10121077]
 [ 0.05626341]]
Mean Squared Loss: 
0.0035099258011622343


Epoch: 
80

#### Extra Credit (*optional*)

Replace all of this text with a brief explanation (~3 sentences) of: 
1. I have some background in both coding and python. When I was younger I took a few very basic intro to coding classes (one taught me how to make simple mods for minecraft in java and the other one was a ~2 weeek intro to python course). Since then I have used python to do some independent projects and had one "class" where someone taught me how some basics of ML and used it to analyze text posts on reddit and classify them by the subreddit they belong to.
2. I did a project that was not covered in the scope of this course, and in doing so I did independent research on how machine learning algorithms work and what they consist of. I also had to learn about a lot of uses of numpy that weren't covered in the course, mainly the way that numpy is used to do matrix calculations, and applied those in my work. Also, even though I had used a machine learning algorithm prior, this was my first time doing it outside of a structered environment where I had someone telling me exactly what to do.